### ISSUE TITLE
deprecate this repo

### ISSUE THREAD

**Issue by lz100** [ucsd-dsm/dsm-docker#1]
Move contain in this repo to dsm-docker**s** if the container is still required, otherwise directly delete this repo.

**Comment by januz** [comment]
@ocelhay I think that we are currently still using this container, right? But I am hoping that we move everything from Shinyapps.io to ShinyProxy and can then delete this repo?

**Comment by lz100** [comment]
I can reformat docker file and gh workflow in this repo and move them to my new repo. If we write new docker files for ShinyProxy, we can simply add new images to [dsm-dockers](https://github.com/ucsd-dsm/dsm-dockers)

**Comment by ocelhay** [comment]
> @ocelhay I think that we are currently still using this container, right? 

Yes, we are still using it for [`abcd-metrics`](https://github.com/ucsd-dsm/abcd-metrics/blob/main/.github/workflows/deploy-app.yaml) and [`recover-metrics`](https://github.com/ucsd-dsm/recover-metrics/blob/main/.github/workflows/deploy-app.yaml).

> But I am hoping that we move everything from Shinyapps.io to ShinyProxy and can then delete this repo?

Here is the status of the different apps:

**`abcd-metrics`  shinyapps.io with container. Beta ShinyProxy ready.**
`abcd-ra-tools` ShinyProxy
`abcd-tlfb` ShinyProxy
`abcd-zoom-attendance` shinyapps.io manual deployment

**`recover-metrics` shinyapps.io with container.**

`hbcd-metrics`  shinyapps.io manual deployment. Beta ShinyProxy ready.
`hbcd-recruitment` shinyapps.io manual deployment
`hbcd-tlfb` shinyapps.io manual deployment

The `hbcd-tlfb` is the one that is going difficult to transition due to the need to coordinate with LORIS.


We probably want to keep the container for `abcd-metrics` (temporary) and `recover-metrics`. @lz100 We can just edit these github workflow files.

@januz I assume switching `recover-metrics` and `abcd-zoom-attendance` apps to ShinyProxy isn't a priority, but something we nevertheless want to do?

**Comment by lz100** [comment]
The new images we plan to build and store on docker hub instead of github. I can rebuild your current image on docker hub, and you just need to change the registry, one line of code, in your github workflow files. Does it sound good?

**Comment by ocelhay** [comment]
> The new images we plan to build and store on docker hub instead of github. I can rebuild your current image on docker hub, and you just need to change the registry, one line of code, in your github workflow files. Does it sound good?

Yes, please add it to dockerhub and send me the link to the image. If it's a public image, I guess that changing one line of code will work.
Thanks!

**Comment by januz** [comment]
Yes, let's do that for now but thanks for the update on the status of deploying apps using ShinyProxy for the different apps. That's something I wanted to talk about later either way :) Agreed that there are a few apps with lower priority but we should try to switch everything over at some point to make maintenance more streamlined (and to save money by cancelling shinyapps.io).

**Comment by ocelhay** [comment]
@lz100 

I am going to replace:

```yaml
    container:
      image: ghcr.io/ucsd-dsm/shiny-rsconnect:main
```

with

```yaml
    container:
      image: hub.docker.com/r/ucsddsm/rsconnect
```

Does it look like a reasonable attempt?

**Comment by lz100** [comment]
```yaml
    container:
      image: ucsddsm/rsconnect:r4.3
```

For default (hub.docker.com), you don't need to specify the registry URL 
also 

```yml
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
```

remove this part. Public images don't need credentials

**Comment by ocelhay** [comment]
That works great - Thanks, Le!
I think we can delete this repo now.
